### ISSUE TITLE
Improvement: API Doc about connect is not clear

### ISSUE THREAD

**Issue by mocheng** [mbasso/refraction-react#1]
In https://github.com/mbasso/refraction-react/blob/master/docs/api.md, It takes me quite a few minutes to understand  the comments.

```
const InputContainer = connect({
  actions: {
    // <Input onChange={refraction.onInputChange} />
    // or if unavailable
    // <Input onChange={refraction.publish.bind(null, 'onInputChange')} />
    // will publish an event on input change
    onChange: 'onInputChange',
  },
  subscriptions: {
    // <Input value={payload} />
    // handle the event and set props.value equals to payload
    // only if is valid, set old value instead (not overwriting it)
    onInputChange: (param, props) => {
      const newProps = {};
      if (param.payload) {
        newProps.value = param.payload;
      }
      return newProps;
    },
  },
})(Input);
```

The comment in `actions` and `subscriptions` is actually counterpart manual coding, right?

**Comment by mbasso** [comment]
Hi @mocheng,
thank you for your feedback.
Yes, comment in `actions` and `subscriptions` indicate how you can obtain the same result without connect function. I can simply underline this adding a sentence before the example:
`N.B. Comments indicate the equivalent code without connect function`

Would you have a suggestion?

**Comment by mocheng** [comment]
@mbasso That is fairly enough. 

BTW. thanks for the cool project on refraction
